### ISSUE TITLE
Secret Decks - Weekly Town Hall - 28th September 2021 -  1900 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [SecretDecks/Documentation#108]
### Participants
Sara, GianLuca, Tyler, Stephen, Mars, Dan
1st time: Felix, John, Jonathan, Robert

https://miro.com/app/board/o9J_lLjDSMY=/

### Intro
- What is Secret Decks ? - Dan
- Why we choose Tarot - Dan, Felix
- More information on "Why Tarot" will arrive soon in the GitBook - Dan

## NFT Drop
- NFT Drop - reaching out to Artists for collaboration - Dan
- For established decks/artists once contracts are clear, it will take another 1-3 months to digitise and animate the content. First drop likely end of year or beginning of next year - Dan
- Interactive part will be most time-consuming - Dan / Tyler

### Retrospective
- https://github.com/SecretDecks/Documentation/discussions/106
- Not all bad - look at positives - Did get a website live briefly & it was a good learning experience- Tyler
- FoundersDrop content was on main site, need to be on subpage - Gian Luca
- Was not reflecting what everybody wanted - Tyler
- Identified problems with workflow - Tyler
- Missing something in the workflow - Gian Luca
  - final check/approval/review on live rollouts needed! 
- We can still use it - Gian Luca
- Founders drop website - we just made it live - we should have done a sprint review - Dan / Tyler
- We change text - we are not organized - we look at things different way- Sara
- Contract with Artist - Gian Luca
- A mini site about founders drop - Online with Site - Gian Luca
- use of artist work as a graphic element - Gian Luca
- Setup a company for domain ownership - Dan, Gian Luca & Tyler
  - explore alternatives for contracts/IP -> *unsplash* or *pixelbay* for contracts, offload IP - Robert
- Code of conduct not respected - not about product - but about collaboration - not really addressing major issues - Felix
- Release meeting prior to website - Gian Luca 
- As a designer - some things to learn - contribute as much as I can - who has the ideas has the heart of the project - Sara
- Different ways people are pushing forward - Gian Luca
- Quite evenly distributed - despite differences - Dan
- Often there is a single person driving a project - but sometimes calm it down a bit - to build a team - Felix
- Before we release anything we should align - Tyler
- The process to arrive at a vote - should not be about a person deciding two names to vote - Gian Luca
- The name finding brainstorm was open to everyone and all have been invited to participate multiple times; we can't put up 5 name options if only 6 or so are voting  - Dan
- Getting a view on what everyone does - engagement is tracked and rewarded - comfort with a tracking tool - Felix
- Do the others know what I do - Felix

### Interactive 
- Brainstorming about terms - Dan

### SourceCred 
- Not working - revert to working version - Gian Luca
- as long as emojis work it is fine - Dan

### Website
- sigma presentation of website - Sara
- Feedback about website - All
- Write links in waterhole channel - Dan
- post page - tests and experimentation - Gian Luca
- Website review - 30th September 2021 - 1900 UTC

### Notes 
- Jonathan had to leave after an hour for a Gimbalabs meeting
- Robert excused himself towards the end

### Action Items
- [ ] Repair SourceCred to have new custom emojis in config
- [x] Create meeting event 
- [ ] test website @SecretDecks/founding-core 
- [ ] Setup agile framework in github (ZenHub!) @DanM3rcurius @stephen-rowan

**Comment by jkochevar** [comment]
Is there a section in Github for the interactive elements? Does this refer to the Tarot mechanism working with the philosophy?

**Comment by stephen-rowan** [comment]
> 
> 
> Is there a section in Github for the interactive elements? Does this refer to the Tarot mechanism working with the philosophy?

Content is a bit dispersed here John - here are some pointers -
- A discussion of the Mindfulness Policy - https://github.com/SecretDecks/Documentation/issues/10
The https://github.com/SecretDecks/Contentwriting repo has - 
- Know thy Self - https://github.com/SecretDecks/Contentwriting/blob/main/Articles/Know-Thyself.md
- SecretDecks to Occultish Newsletter - https://github.com/SecretDecks/Contentwriting/blob/main/Newsletters/SecretDecks%20to%20Occultish.md
- the Discussions Board in the Docs repo - https://github.com/SecretDecks/Documentation/discussions

**Comment by DanM3rcurius** [comment]
@jkochevar If you like we can do a brainstorm/feedback session on the Major arcana concept I've been drafting past weeks. 
Once I'm done with the basic agile framework setup we can get to work on it!

**Comment by jkochevar** [comment]
@DanM3rcurius I'm down for a brainstorm session. I am still not familiar with Tarot as much, but would be happy to try my best!
