### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by stephen-rowan** [SecretDecks/Documentation#112]
# User Stories
## User Story no.1:

As an artist I have created my own deck and would like to create a digital copy as NFT collectibles and offer them for sale; 
I see an image of a card on the main page that reads: "Are you an artist?"; 
I immediately feel this is the card I want to select

*-> Links to Artist collab. section with discord invite link*

## User Story no.2:
As an NFT collector I'm always looking for the newest, hottest drops and interesting communities to "invest in" early on if possible; 
I see an image of a card on the main page that reads: "Are you a NFT collector?";
I immediately know this is the card for me to select, in order to find out about the first and hopefully a little info on future drops

*-> Links to DROPS (teaser) and call to action in the teaser section for FoundersDrop*

## User Story no.3:
As a Tarot enthusiast I want to engage with the Tarot on new levels;
I see a well known card on the main page "XXI - The World";
I immediately know this is the card for me to select in order to find out more about the Tarot metaverse 

*-> Links to GitBook "The metaverse"*

## User Story no.4:
As someone who has knowledge about governance and self organising communities, I'm interested in shaping the governance tools of tomorrow; 
Since I'm naturally curious I see a navigation point that says "Governance in the DisCo";
I have a strong sense that this is what I need to select to find out more about what interests me

*-> Links to GitBook "how we do stuff"*

**Comment by DanM3rcurius** [comment]
Maybe using GitHub pages?

**Comment by DanM3rcurius** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SecretDecks-Website-Relaunch--Founders-Drop-615413e56a2e7e0012d7f67b/issues/SecretDecks/Documentation/112?planning-poker) with ZenHub @stephen-rowan @wlstylr

**Comment by wlstylr** [comment]
All done 🙏
