### ISSUE TITLE
Sprint Meeting - Monday 4th October 2021

### ISSUE THREAD

**Issue by stephen-rowan** [SecretDecks/Documentation#116]
## Sprint Meeting - Monday 4th October 2021
# Prep & Agenda
### Why Agile?
To accommodate for the following:
- distributed / asynchronous work/ workflows
- incremental design, creation and rollout of relatively complex systems
- better communication flows
- easier reporting & contribution tracking
- more streamlined meetings
- focus attention, reduce multitasking / task switching 
- start automating workflows

#### Terminology
- **Story:** refers to "user story" -> what is the person interacting with the feature or feature set seeing and experiencing; How is the person doing what and why from the I-perspective
- **Epic:** refers to "Epic Story" -> A story that is quite large (or multiple stories) and can't be completed within 2-3 days
- **?** What else is not clear?

#### Tools used
- **Sprints** 
 A defined period of time that is nested between planning and review gatherings.
  * Sprint Planning: a team effort to slice actionable tasks from defined epics; an estimation poker should accompany or precede the planning!
  * Review Gathering: a gathering of all teams at the end of the sprint to review the work accomplished
- **Estimation Poker**
 Asynchronous estimation of stories (epics) and tasks, in order to approximately predict what can be successfully committed and accomplished in 1 Sprint.
- **Retrospective**
  * On demand (usually at least after each milestone), interactive gathering to find out how we did things in the previous weeks, what was good and what was not so good
- **Online tools**
  * Interactive Kanban board: to visualise workflow in "pipelines"; the "in progress" pipeline is always limited to how many items can be worked on at any given time.
  * TeamWorkSpace in ZenHub: generates the Kanban board, reporting data, roadmap & timelines; milestone management; automates handoffs between teams, so much more! ; used instead of GitHub projects

# SD SprintPlanning 
start: 8:30ish end: 11:20pm UTC+2
## Attendees
Matti, Quasar, Heather, Stephen (joined later), Tyler, Dan

## Why Agile?
- read prep - Dan
- showed Sprint process visual - Dan
![SprintPlanning-intro](https://user-images.githubusercontent.com/80257662/136105140-3202d48e-b513-476f-a985-eb87e88c2308.jpg)

- Why agile? Allows to focus on 1 specific task / feature /... ; keeps us building continously - Tyler

- family has antiques, also some antique Tarot decks, can share them - Matt

## SprintPlanning
- writing Stories specs and tasks - all

- Contribution survey automation, raised an issue for  rework - Stephen

- Marketing for website should get extra story - Stephen

- Story for "us" / "the forgotten story" / Do we funciton as we want to function; integrate into Retrospective - Tyler

- Mention of NFTSeed buy process - Tyler

- Dan will continue on Epics

**Comment by DanM3rcurius** [comment]
Definitions
Review meeting: What?
Retro meetings: How? positive / negative
