### ISSUE TITLE
20211204 - [VotingReport] - DisCo Name

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#148]
## Discord Voting Link
**[Link to poll](https://discord.com/channels/839844883124584478/884143672004857936/916778526122844220)**

## Type
*Please select one and delete others*
- [ x ] poll (72h max)

## Date, Time
- *start: 4th Dec 2021 7:50 pm UTC* | *end: 6th Dec 11am UTC* 

## Question
**What should be the name for the DisCo legal entity?**

## Answers & tallies 
- **A** *GitDisCo* (Governance in the DisCo) - **3.5 Votes**
- **B** *DisCoTec* - **3.5 Votes**
- **C** *SelfSoulstain* - **1.5 Votes**
- Optional: *insert screenshot of results*

![Screenshot 2021-12-06 at 13 52 52](https://user-images.githubusercontent.com/80257662/144849385-6c84b0d9-6155-4197-b1f2-86e6d26606e2.png)

## Action Item
- [x] Buy domain DiscoTec
- [x] conceptual design of GitDisco product

## [optional] Proof of Done (PoD)
Domain bought
![Screenshot 2021-12-07 at 00 10 12](https://user-images.githubusercontent.com/80257662/144937440-464fa6e5-c1b6-4441-aa99-706735717a2c.png)

**Comment by DanM3rcurius** [comment]
@wlstylr please approve and oversee

**Comment by wlstylr** [comment]
@DanM3rcurius I approve, and will post results in Discord

**Comment by wlstylr** [comment]
Nevermind; I see you already posted the results.  Will still oversee the rest
