### ISSUE TITLE
2021-12-Pythagorean-SecretDecks-ContributionSurvey

### ISSUE THREAD

**Issue by Pythag0rean** [SecretDecks/Documentation#166]
### Date Joined SecretDecks

11/27/2021

### Hours Worked (This Month)

1

### Contribution Peer Review

Dan

### Teams (Teamworkspaces) contributed to

- [ ] Website
- [ ] Governance
- [ ] Content & Metaverse

### Output

Recruited Cipher, Kathi, Mike.

### Intangibles

- [X] Greeting new members
- [ ] Mentoring
- [X] Social / Emotional Support
- [X] Communicating news and ideas in Discord

### (felt) Output

Invited in high quality members including Mike who helped build

### Team External Work

Recruitment, Bridge building between Secret Decks and Beanchain

### Hours Worked (This Month)

1

### Local Hourly Rate (USD)

125

### Total Costs

125

### ADA/USD Exchange Rate

1.31

### Total Remunerations (ADA)

95

**Comment by DanM3rcurius** [comment]
Oh damn. I completely overlooked this -.-
So sorry, please excuse me!
I absolutely approve 🙏🏿  
Please ping me with an @ mention in case I'm not reacting.
