### ISSUE TITLE
2021-12-Michael-Baldwin-SecretDecks-ContributionSurvey

### ISSUE THREAD

**Issue by mbaldwin2015** [SecretDecks/Documentation#175]
### Date Joined SecretDecks

12/07/2021

### Hours Worked (This Month)

1

### Contribution Peer Review

Dan

### Teams (Teamworkspaces) contributed to

- [ ] Website
- [X] Governance
- [ ] Content & Metaverse

### Output

Contribution Survey v.01

### Intangibles

- [ ] Greeting new members
- [ ] Mentoring
- [ ] Social / Emotional Support
- [ ] Communicating news and ideas in Discord

### Hours Worked (This Month)

1

### Local Hourly Rate (USD)

50

### Total Costs

50

### ADA/USD Exchange Rate

1.03

### Total Remunerations (ADA)

48.5

**Comment by DanM3rcurius** [comment]
very much approve!
