### ISSUE TITLE
year(number)-month(number)-your-name-SecretDecks-ContributionSurvey

### ISSUE THREAD

**Issue by dgarey** [SecretDecks/Documentation#202]
### Date Joined SecretDecks

01/1/22

### Hours Worked (This Month)

30

### Contribution Peer Review

Dan

### Teams (Teamworkspaces) contributed to

- [X] Website
- [ ] Governance
- [X] Content & Metaverse

### Output

This week I connected the Arcana Gitbook to Secret Decks Discord. My main focus has been continued examination of our reporting Bot, and trying to extend the times of monitor passed 1 day increments. The Last example of this testing can be found in issue #190-#198. Upon inspection of the bot source code, I was able to find a typo in "weak", which may well be why the weekly option is not registering. i have submitted a PR request with MIT, the owner of the Repo.  I currently have changed the schedule back to weekly and will see the report when it runs on Sunday. All test scheduled at daily increments produce a report, but with no relevant information for previous issues handled. I discussed and proposed another report to Dan, in which the graphical interphase was nice, but the information only pertained to open issues, and would not provide enough information to be an aid for the contribution survey. 

### Intangibles

- [ ] Greeting new members
- [ ] Mentoring
- [ ] Social / Emotional Support
- [X] Communicating news and ideas in Discord

### Team External Work

Github/Discord Dev Work

### Hours Worked (This Month)

30

### Local Hourly Rate (USD)

55

### How much % of your contribution is pro-bono?

10

### Other Expenses (USD)

I have been paid 50% of my agreed-upon bounty at my request. I greatly appreciate this. 

### Total Costs

1650

### ADA/USD Exchange Rate

2.13ADA/USD

**Comment by DanM3rcurius** [comment]
Awesome work, thanks  Dom!
Do you think it'll be possible to catch the commits in the GitBook as well? If not we have to find a work around

idea a) (bad one) track work done in GitBook via issues in GitHub repo
idea b) (maybe better) have GitHub repo as source and sync to GitBook (currently we work in Gitbook and it syncs it back to GitHub)

**Comment by DanM3rcurius** [comment]
This contribution is related to the [PCS Fund7 proposal](https://github.com/SecretDecks/Catalyst-Proposals/issues/12)

**Comment by DanM3rcurius** [comment]
@dgarey What made you ignore the title? not present enough? should /can we have it as an input box as well, so it won't get ignored?

**Comment by dgarey** [comment]
Yes. I think we already have em catching!
