### ISSUE TITLE
Procuring hardware for bm pool setup

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#210]
The TAROT pool is moving to a bare metal infrastructure (2 raspberry pi's 4 with 8GB and 1 TB m.2 SSD each).

So far procured:

For pool node

- [x] Raspi 150€
- [x] Case 47€
- [x] SSD 98€

For relay node

- [x] Raspi 
- [x] Case 40€
- [x] SSD 98€

**Comment by dgarey** [comment]
Please let me know if you have any questions or concerns related to setup

**Comment by DanM3rcurius** [comment]
I got all hardware together now. Will close this and open a ticket for the setup, I'll tag you there.
