### ISSUE TITLE
Github workflow visualisation

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#29]
## Goal 
Visualise current workflow within github for collaborative creation of documents

_Originally posted by @DanM3rcurius in https://github.com/SecretDecks/Documentation/discussions/4_

## Basic worklfow
github workflow:

1. Fork repositories (you want to edit in)
2. edit content (change, correct, add or remove) 
3. open pull request [PR] (to push changes to main repository)
4. ask for PR review (tag reviewer(s))
5. [optional] discuss PR 
-> PR merged!

## Best Practices 

- It is prudent to request that everyone works from forks of the repos (so there is consistency in tracking and ease in reverting everyone's changes).
- It is OK for everyone to merge their own pull requests - as long as comments are left for major changes (small changes such as correcting spelling are usually self-explanatory).
- It should be generally accepted that other members may revert your pull request if they give a good reason (like adhering to a style guide).
- It is good practice to "semantically" merge pull requests - that is, submit a pull request every time a change that can be described has occurred (this helps people check an audit trail later on).

It is probably a good idea to summarise this GitHub Workflow and incorporate it into the SecretDecks "contributions policy" (a standard open-source doc). So people have just one place to go to learn how to contribute, use GitHub and refer to standards (such as style etc.).

- Requirements to establish tiered permission structure for merging pull request  
	- At least 2 Maintainers/Admins per repo
	- recommended when review required pull requests become more often (>2 times a day)

**Comment by DanM3rcurius** [comment]
If work on an issue/task has begun, assign it to you (optional) and pull it into the "doing" column of the kanban board (mandatory)

**Comment by DanM3rcurius** [comment]
<img width="1035" alt="Screenshot 2021-06-02 at 17 12 42" src="https://user-images.githubusercontent.com/80257662/120505974-ca9a1000-c3c5-11eb-888b-3f91f7bf4098.png">

Thoughts about this @wlstylr @stephen-rowan and maybe @tamagit80 ?

**Comment by tamagit80** [comment]
Sorry guys didnt see this msg before.
Soo I think that from "not approved" it should go back to "Check related",
not start task :)
ciao g.

**Comment by DanM3rcurius** [comment]
<img width="1173" alt="Screenshot 2021-06-03 at 14 39 45" src="https://user-images.githubusercontent.com/80257662/120646272-a4ce4300-c479-11eb-8adf-7c4d84f99172.png">

makes sense, also makes the diagram smaller👍🏿 
like so? @tamagit80

**Comment by DanM3rcurius** [comment]
<img width="1166" alt="Screenshot 2021-06-03 at 14 53 12" src="https://user-images.githubusercontent.com/80257662/120647940-6e91c300-c47b-11eb-902c-c1bb28d60cc6.png">

I was thinking about how to structure the flow of discussions (around ideas), the above is what I came up with for starters.
Thoughts @stephen-rowan @wlstylr  ?

**Comment by stephen-rowan** [comment]
I am taking the approach of Discussions first (only for major ideas / changes)
So something like ...

1) Check if Idea is in discussions already 
2a) If Idea is in discussion already - add a comment to document what you want to change.
2b) If Idea is not in discussion - add a discussion to document what you want to change.
3) Add new Idea via Pull Request (with links to discussion).
4) SecretDecks decides whether to go with or revert pull request.

This is a simple self-documenting dynamic system that allow members to go forward with their Ideas. It does depend upon other members reverting or amending Ideas later.

In my view Issues should be reserved only for tasks that need to be tracked in a Project Board. 
Tasks are either ...

- 1) Major - e.g. "Github workflow visualisation"
- 2) Minor - e.g. bugs, quick fixes.

Sometimes it makes more sense to convert Issues with a lot of comments into a Discussion (which would disappear the Issue) rather than close them. 

There are many ways to use GitHub - we will find what suits us best with trial and error !

**Comment by stephen-rowan** [comment]
## Issue Allocation workflow

This diagram (https://github.com/SecretDecks/Documentation/issues/29#issuecomment-853837818) is a good workflow to follow when working with Issues or Pull Requests. 

- At this early stage it is a good idea to "fetch upstream" in your local repo - to avoid possible conflicts. (As we become more adept at GitHub we will be able to work on parallel forks)
- We will probably need to explain what we main by "Semantic" PR in more detail - I will draft something for the contribution file at some point.
- I think Reviews should be reserved for specific reasons as they slow up the process. Large repos often require everything is reviewed a small community like SecretDecks can rely on reverting unwanted changes. This excludes special cases where we want someone to review what we have changed - for example I ask for a review if I have changed someone else's work like this [pull request](https://github.com/SecretDecks/Documentation/pull/37) on the Contributions Template.

**Comment by wlstylr** [comment]
## Discussion Flow
@DanM3rcurius your diagram aligns with how I intuitively thought the process should be structured.   It provides a clear visual that describes a pathway for an idea to become an actionable item (issue).    I think it may make sense for the diagram and text description to find a place to live on the discord server.  We want to provide folks with clear instruction on how to ensure their ideas don't get orphaned on an island.  

## Working with Issues or Pull Requests workflow

- Agree with @stephen-rowan regarding "fetch upstream."  I have a feeling this could be something easily missed by people new to Github. 
-  Same with "Semantic"
- Agree that reviews should be reserved for specific reasons, but perhaps we should have a system in place where folks newer to SD have all PRs reviewed before merge?   I understand we can revert changes, but it could become tiresome and confusing if we are in a situation where we are reverting multiple PRs in succession due to user error such as forgetting to "fetch upstream" before PR and merge.

**Comment by tamagit80** [comment]
perfect :) Yesterday was the whole day a work :)

**Comment by DanM3rcurius** [comment]
> ## Discussion Flow
> I am taking the approach of Discussions first (only for major ideas / changes)
> So something like ...
> 
> 1. Check if Idea is in discussions already
> 
> 2a) If Idea is in discussion already - add a comment to document what you want to change.
> 
> 2b) If Idea is not in discussion - add a discussion to document what you want to change.
> 
> 1. Add new Idea via Pull Request (with links to discussion).

What do you mean by the above?
So far what I understood:

<img width="1009" alt="Screenshot 2021-06-04 at 20 42 08" src="https://user-images.githubusercontent.com/80257662/120848658-57370080-c575-11eb-98b3-51f351b5ca16.png">


> ## Issues
> In my view Issues should be reserved only for tasks that need to be tracked in a Project Board.
> Tasks are either ...
> 
> 1. Major - e.g. "Github workflow visualisation"
> 2. Minor - e.g. bugs, quick fixes.
> 
> Sometimes it makes more sense to convert Issues with a lot of comments into a Discussion (which would disappear the Issue) rather than close them.

Yes that's what I'm missing with discussions. They're not represented in the project board.
I was under the impression that every discussion (be it of an idea, improvement or new feature) concludes in some actionable item(s) that in many cases %0% or more are major or minor "issue", which can be tracked, assigned and mapped in a PR. Do we have the same capabilities  with discussions? 

> 
> There are many ways to use GitHub - we will find what suits us best with trial and error !

We sure will <3

**Comment by DanM3rcurius** [comment]
> ## Working with Issues or Pull Requests workflow
> This diagram ([#29 (comment)](https://github.com/SecretDecks/Documentation/issues/29#issuecomment-853837818)) is a good workflow to follow when working with Issues or Pull Requests.
> 
> * At this early stage it is a good idea to "fetch upstream" in your local repo - to avoid possible conflicts. (As we become more adept at GitHub we will be able to work on parallel branches)
> * We will probably need to explain what we main by "Semantic" PR in more detail - I will draft something for the contribution file at some point.

Yes! Both points will be incorporated into the GitHub onboarding tutorial, thanks Stephen
!
> * I think Reviews should be reserved for specific reasons as they slow up the process. Large repos often require everything is reviewed, but a small community like SecretDecks can rely on reverting unwanted changes. This excludes special cases where we want someone to review what we have changed - for example I ask for a review if I have changed someone else's work like this [pull request](https://github.com/SecretDecks/Documentation/pull/37) on the Contributions Template.

Agreed! Trying to weave this in when I touch the diagram the next time!

**Comment by DanM3rcurius** [comment]
> * Agree that reviews should be reserved for specific reasons, but perhaps we should have a system in place where folks newer to SD have all PRs reviewed before merge?   I understand we can revert changes, but it could become tiresome and confusing if we are in a situation where we are reverting multiple PRs in succession due to user error such as forgetting to "fetch upstream" before PR and merge.

Yes! Maybe until they reach Level 2 of the core layer?

**Comment by stephen-rowan** [comment]
Replying to : https://github.com/SecretDecks/Documentation/issues/29#issuecomment-854930923
Yes, your diagram is starting to approach what I mean.

>Yes that's what I'm missing with discussions. They're not represented in the project board.
> I was under the impression that every discussion (be it of an idea, improvement or new feature) concludes in some actionable item(s) that in many cases %0% or more are major or minor "issue", which can be tracked, assigned and mapped in a PR. Do we have the same capabilities with discussions?

Yes- I agree …

1)	When you begin with an idea you should express first in documentation (like a draft) and the best place to do this is in a discussion. This starts to document the idea (which is often missed) and allows others to comment in general. 
2)	This then “concludes in some actionable item(s)” as you say. 
3)	Then an Issue is raised for the Idea (or task etc.) and this finds a home in some Project Board (How to organise Project Boards is another thing we may need to work out).
4)	Then the Issue can be tracked and Pull Requests can be linked to that Issue ?

For example …

1)	I want to create a new “xyz document” – so I start a discussion on “xyz document”, explain what I want to do and get comments.
2)	Everyone agrees that a new “xyz document” is a good idea so it becomes an actionable item.
3)	I then raise an Issue “Draft xyz document” and assign it to “To Do “ in the “Documentation” Project Board.
4)	I then work on “xyz document” via Pull Requests which I link to the “Draft xyz document” Issue ?

**Comment by DanM3rcurius** [comment]
<img width="1152" alt="Screenshot 2021-06-04 at 23 37 07" src="https://user-images.githubusercontent.com/80257662/120865168-ca4c7100-c58d-11eb-8da1-8eeb79d6d62d.png">

Found a possible solution for the onboarding automation of the shell approval with a bot

**Comment by DanM3rcurius** [comment]
> For example …
> 
> 1. I want to create a new “xyz document” – so I start a discussion on “xyz document”, explain what I want to do and get comments.
> 2. Everyone agrees that a new “xyz document” is a good idea so it becomes an actionable item.
> 3. I then raise an Issue “Draft xyz document” and assign it to “To Do “ in the “Documentation” Project Board.
> 4. I then work on “xyz document” via Pull Requests which I link to the “Draft xyz document” Issue ?

Like so?:

![DAO BrainStorms - Github-Idea-Workflow](https://user-images.githubusercontent.com/80257662/121188139-1981f280-c869-11eb-8f65-b0170e1d6142.jpg)


BTW the [source files can be found here](https://miro.com/welcomeonboard/MWNpT1c5NnhYT0RKV0Vla1dxNndndkhxYnU4aEN5SU00dDVpcHJoWjlOV2VQME9CbkhWbGtlSXBWYTNzVlQySnwzMDc0NDU3MzQ3MTQ0OTYzNjgz)

**Comment by stephen-rowan** [comment]
Responding to https://github.com/SecretDecks/Documentation/issues/29#issuecomment-856739477

Yes that is pretty much it. I guess the graphic should be incorporated in the SecretDecks Contributions file under a GitHub section ?

**Comment by DanM3rcurius** [comment]
Not sure if I fully understand what you mean with "should be incorporated in the SecretDecks Contributions file under a GitHub section ?"
To mention it in the contribution survey? Or to create a section in the Survey for GitHub contributions (does that even make sense?)

warm regards
D

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by stephen-rowan** [comment]
Yes its easy to confuse what I said with the contribution survey. 

But I mean a Contribute.md file like this (https://github.com/Quality-Assurance-DAO/DAO-Open-Source/blob/main/Contribute.md). Which SecretDecks does not have yet and is part of an open-source minimum requirement.

S

**Comment by DanM3rcurius** [comment]
Oh nice! Will edit a copy for the SD repo now. Thanks Stephen!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanM3rcurius** [comment]
the basic visualisation is done on the miro board. I'll close this task now. I added the reference to here in the contribute.md. Don't know how to add images into .md files 😅
https://miro.com/welcomeonboard/MWNpT1c5NnhYT0RKV0Vla1dxNndndkhxYnU4aEN5SU00dDVpcHJoWjlOV2VQME9CbkhWbGtlSXBWYTNzVlQySnwzMDc0NDU3MzQ3MTQ0OTYzNjgz

**Comment by stephen-rowan** [comment]
Miro Board link are proprietary  - take a screen shot and drag the file into the comments like this 

![2021-07-10 (1)](https://user-images.githubusercontent.com/25156451/125177261-3e53e780-e1d2-11eb-9bc4-a38f25b8fc18.png)
