### ISSUE TITLE
workshop/review the contributions survey!

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#56]
@DanM3rcurius , @evolayak - I suggest we workshop/review the contributions survey to completely revise it to our needs. A lot of the categories were included for NFT-DAO. We could do this as a meeting or just share a markdown version on GitHub and revise from there ?

_Originally posted by @stephen-rowan in https://github.com/SecretDecks/Documentation/issues/44#issuecomment-860595662_

**Comment by stephen-rowan** [comment]
Reply to https://github.com/SecretDecks/Documentation/issues/56#issue-929020016

There is already a markdown version here we can revise https://github.com/SecretDecks/Documentation/blob/main/surveys/contribution/template-contribution-survey.md

**Comment by DanM3rcurius** [comment]
closing this, work continues in #119

**Comment by DanM3rcurius** [comment]
Issue moved to [SecretDecks/Distributed-Work-Reward-Mechanism #1](https://github.com/SecretDecks/Distributed-Work-Reward-Mechanism/issues/1) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DanM3rcurius** [comment]
Issue moved to [SecretDecks/Distributed-Work-Reward-Mechanism #2](https://github.com/SecretDecks/Distributed-Work-Reward-Mechanism/issues/2) via [**ZenHub**](https://www.zenhub.com/)
