### ISSUE TITLE
Research : Off-Chain Polling

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#57]
# Goal
A process to do (quick) polling within the community. 

# Specs
- Quick polling via Off-Chain voting mechanism (Discord polling bot?)
-  high impact decisions vi On-Chain voting/polling
- When should we use the term voting, when polling? or only polling?

**Comment by DanM3rcurius** [comment]
played around on testserver with following bots:
- [EasyPoll](https://easypoll.me/)
- [PollBotPlus](https://discordbotlist.com/bots/pollbotplus)

I favour PollBotPlus, it has same features as EasyPoll but better (easier interface)

@wlstylr @tamagit80 @stephen-rowan thoughts?

**Comment by wlstylr** [comment]
I also prefer PollBotPlus

**Comment by stephen-rowan** [comment]
## Some prerequisites

What are you trying to achieve with polling? (We need to be able to explian our rationale).

How does this fit with SD governance? (e.g. when does AGILE stop and Governance start). 

The nomenclature varies between countries (e.g., in the UK General Election you vote in a polling station).

Perhaps make a distinction between - 

Polls - quick and dirty for AGILE - low impact - define

Voting - slow and detailed for governance - high impact - define

**Comment by wlstylr** [comment]
I created a follow up issue to this research issue [here](https://github.com/SecretDecks/Documentation/issues/61)
I thought it made sense to break up research and execution into two separate issues.  
Cool?

**Comment by DanM3rcurius** [comment]
Very cool!

**Comment by DanM3rcurius** [comment]
finishing up my research from d10 gov and will add notes that fit in the issue #61 that @wlstylr  created!
