### ISSUE TITLE
Rework "Why" slide of gov presentation 

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#73]
Context: the presentation should give a brief overview of where we are with the government design as well as where we want to go how. Very basic, for people who think governance is about making a cross  on a piece of paper (;

This is the current WHY slide in the gov presentation

> A stewardship layer provides us with a toolset to...

>formalise an egalitarian merit based group decision making process,

> build a path to find consensus and resolve conflict,

> ...in a human manner enhanced by automation where possible.

**Comment by wlstylr** [comment]
A transparent and well defined governance layer is essential for long term sustainability.  During this first phase we intend to steward Secret Decks towards this goal by introducing a toolset to...

- Formalize an egalitarian merit based group decision making process,
- build a path to resolve conflict and reach consensus,
- ensure that humanity is not obscured by automation,
- allow for iteration and evolution

**Comment by stephen-rowan** [comment]
For a distributed community to be sustainable is must define how it governs itself clearly and transparently.
At first, we will steward Secret Decks towards this goal by building a toolset that:
•	Will formalize an egalitarian merit-based decision-making process.
•	Will build pathways that resolve conflict through consensus.
•	Will ensure that our humanity is not obscured by automation.
•	Will allow for iteration and evolution.

**Comment by wlstylr** [comment]
@stephen-rowan I like your revision :)
