### ISSUE TITLE
design & create custom Discord emojis to better distinguish "SuperCred" generating emojis (@wlstylr ?)

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#76]

**Comment by wlstylr** [comment]
@DanM3rcurius  What do you think?
![Screenshot 2021-07-30 12 56 19 PM](https://user-images.githubusercontent.com/58446163/127705507-de674f9c-171c-4b02-a551-2cc3ab42022c.png)
CAN-D pill =1 , CAN-D bottle = 2, Euphoric Heart =3, Chrystal Ball =4,  - 1 = -1

link to discord - https://discord.com/channels/849529452550946816/849529452550946825

**Comment by stephen-rowan** [comment]
Reply to https://github.com/SecretDecks/Documentation/issues/76#issuecomment-890123426
Love it ! :alien:

**Comment by DanM3rcurius** [comment]
wow! Seeing them now for the first time - let's use em now!
Amazing work @wlstylr

**Comment by wlstylr** [comment]
Now added to Discord :)

**Comment by DanM3rcurius** [comment]
@wlstylr do you want the honour of closing this?

**Comment by wlstylr** [comment]
Closing now:)
