### ISSUE TITLE
Catalyst Fund 6 - Submit Proposal Drafts

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#81]
# Catalyst Fund 6 - Proposal

# "The Fool" / "Page of Wands"

## Problem
	- Epic Problem: DAO trust / verification is currently impossible
	
**Problem Slice**: Tracking of (community) care & pro-bono work, outside the technical scope, in a DAO like structure is difficult. Allocating and validating value to the data and distributing rewards accordingly, has not yet been properly done. We see this as a huge impediment, for how can distributed communities become self sufficient/governing when there's no mechanism to reward individuals fairly that do (community) care & pro bono work.
- **SHORT CATALYST VERSION**: Tracking, rewarding & validating care (intangible!) & pro-bono work in a DAO like structure, outside tech. scope, is difficult & complex.

## Solution
Care & pro bono work reward (real life) test case in an emerging DisCo environment. A "Distributed Work-Reward Mechanism".
We offer our small but diligent community as a self case study. The goal is to share insights into how we track care & pro bono work, attribute value, validate it and distribute rewards accordingly.
Measurable goals would be: a Gitbook chapter on "Distributed Work-Reward Mechanism"; a tool template and tutorial / educational content on the mechanism.

- **SHORT CATALYST VERSION**:  Test driving the mechanism in an emerging DisCo environment and sharing all insights.

## Relevant Experience
SecretDecks has 5 core members working since April. Backgrounds in Product- & Project Mngmt, Editorial, Philosophy & web development.

## Details
We use GitHub to track task items, creation of written content, wiki (Gitbook), Ideas, Meeting minutes.
We use Discord for informal and formal communication.
We setup a SourceCred instance to aggregate data from GitHub & Discord and distribute "Can-D" according to the amount of positive or negative contributions or reactions each individual member has impacted within the community.
Additionally we have a manual process for core members to attribute value to their work via a monthly "Contribution Survey" (big thanks and applause to @Stephen for initiating this back in the NFTDAO days!), this survey gets validated/reviewed by at least two other team members for final approval.
How and for what "Can-D" be exchanged or redeemed for we yet have to find out.

## Why is it a problem?
One of the main reasons individuals can't transition out of their employment / Game A position, is that distributed organisations or cooperatives don't have a trusted & working mechanism to track, attribute value to & successively reward contributions of individuals (except if it's committed code in Git).
We believe Cardano and the community carrying it can change that, by nurturing many small pools of communities (that cluster around an idea / project). See those pools building self governance tools, using them and sharing all findings or insights.

**Comment by wlstylr** [comment]
### Alternative problem statement:
Rewarding intangible work in a DAO should be transparent and scalable. However, a focus on $ allocation before attribution stymies growth.

**Comment by DanM3rcurius** [comment]
> ### Alternative problem statement:
> Rewarding intangible work in a DAO should be transparent and scalable. However, a focus on $ allocation before attribution stymies growth.

Much better and more precise, what do you think @stephen-rowan ?

**Comment by wlstylr** [comment]
And an alternative to the solution statement:

"An open-source attribution, valuation, and rewarding framework gleamed from the Secret Decks emerging DisCO environment."

**Comment by stephen-rowan** [comment]
**Problem Statement** : "Rewarding intangible work in a DAO is not transparent or scalable. There is too much focus on $ allocation before contribution attribution." 139 Char

**Comment by stephen-rowan** [comment]
**Solution Statement** : "Develop an open-source attribution, valuation & reward framework based on a Distributed Co-Op approach."

**Comment by stephen-rowan** [comment]
In the detailed plan I would start with "Why is it not having this mechanism a problem?" - then expand upon the solution. The detailed solution should be presented as a logical progression, with milestones/roadmap and deliverables.

**Comment by DanM3rcurius** [comment]
> **Problem Statement** : "Rewarding intangible work in a DAO is not transparent or scalable. There is too much focus on $ allocation before contribution attribution." 139 Char

Even better, sounds even more like a problem, a serious one that is.

**Comment by DanM3rcurius** [comment]
> **Solution Statement** : "Develop an open-source attribution, valuation & reward framework based on a Distributed Co-Op approach."

And another cherry on top of @wlstylr improvement! Well done gentlemen 👏🏿

**Comment by DanM3rcurius** [comment]
Updated the proposal just now!

**Comment by DanM3rcurius** [comment]
@tamagit80 in weekly today: mention that SD is the pilot for the system the reward mechanism is used in

**Comment by DanM3rcurius** [comment]
Thanks everyone for your help! Will close this now and open a new issue for refinement of each proposal
