### ISSUE TITLE
Catalyst Fund 6 - Easy UX Proposal

### ISSUE THREAD

**Issue by wlstylr** [SecretDecks/Documentation#82]
# Catalyst Fund 6 - Easy UX Proposal

## Propblem
UX within distributed organisations is problematic especially for non technical individuals.

## Solution
Create first iteration of easy to use tools for transparent & distributed collaboration

## Relevant Experience
Currently 5 active core members working since April. Backgrounds in product- & project management, editorial, philosophy & web development.

## Details

- Identify different types of DAOs
    - Creator DAO
    - Investor DAO
- DAO modules
    - Onboarding / orientation 
    - Treasury
    - Voting
    - Contribution first 
    - Bounty first

**Comment by DanM3rcurius** [comment]
should we document the proposals here as well @wlstylr ? If not then we can close this issue?

**Comment by wlstylr** [comment]
@DanM3rcurius I think we can close this.  I had opened to start a draft outside of IdeaScale, but not needed anymore in my opinion.  I'll close for now.
