### ISSUE TITLE
Fund 6 Proposal - DistributedWorkReward

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#86]
# Summary
continuing from #81, this issue here is tracking the refinement of the proposal.
🔗  [DistributedWorkReward mechanism voting proposal link](https://cardano.ideascale.com/a/dtd/Distributed-Work-Reward-Mechanism/368091-48088)🔗

TBD:
- [x] Budget breakdown
- [x] Milestone plan
- [x] Detailed execution
- [x] SecretDecks intro

## Budget Breakdown

**TOTAL: 261 ADA**

## Milestone plan
- MS0: basic tracking of contributions across different channels and spectrums (intangible & tangible) for more than two months; Setup SourceCred (to distribute social/community currency) and custom emoticons for Discord
- MS1: Try out distribution of social currency,  Setup exchange of social currency to gov tokens

**Comment by wlstylr** [comment]
## Possible use for Can-D (SecretDecks contribution token)

- To build voting power (early and consistent contributors to opensource projects should have a voice)
- To mint Founder NFTs 
-  Exchange for ADA or stable coin (long term)

Oftentimes early organizations that are attempting to bootstrap a project do not have liquidity available to compensate early contributors to said project.  Attracting collaborators can be difficult without a clear path outlining how immediate effort can be exchanged for delayed compensation.  

### Progress thus far

- SecretDecks has setup a SourceCred instance that has been configured to track contributions made through Discord and Github.  
- A manual process for attributing value through a "Contribution Survey" has been implanted.  This allows for the automated rewards mechanism to be compared and contrasted to manual self assessment, which in turn provides information that helps to fine tune the automation.

### Short term objectives

- Refine SourceCred instance 
- Mint and distribute contribution tokens (Can-D)
- Enable Can-D to NFT exchange
- Enable Can-D to affect voting power
- Experiment with contribution driven tokenomics model


### Deliverables

- A Gitbook chapter on "Distributed Work-Reward Mechanism"
- Tool template and tutorial
- ????

**Comment by wlstylr** [comment]
@DanM3rcurius some ideas ⬆️

**Comment by DanM3rcurius** [comment]
Proposal submitted.
Created new issue #95 with your comment @wlstylr
